[enhancement] Improve the UX of Manage folders screen: Hide Add Folde…
ARK-Builders/ARK-Navigator pull request #401
Opened 2023-10-17 15:46 UTC by tuancoltech

Improve the UX of Manage folders screen by hiding Add Folder button when reaching bottom item of the list.

2023-10-18 06:16 UTC, mdrlzy requested changes
If list is not full screen, scroll hides fab forever
<details>
<summary>Screenshot</summary>

![image](https://github.com/ARK-Builders/ARK-Navigator/assets/85668474/009308eb-0884-460e-8c0b-477c0d9a8a77)
</details>

2023-10-18 15:07 UTC, tuancoltech commented
> If list is not full screen, scroll hides fab forever
> 
> Screenshot
> ![image](https://user-images.githubusercontent.com/85668474/276116913-009308eb-0884-460e-8c0b-477c0d9a8a77.png)

@mdrlzy Thanks, that's a good catch.
I just changed the solution to a simpler strategy: Increase the list bottom padding.
Please re-review.

2023-10-19 15:28 UTC, tuancoltech commented
> So far so good. Could you please spend a bit more time on trying other solution for this improvement? Adding padding at the bottom might reduce our space and lead to a big empty space in our screen. Just found this article to handle fab effect. Please give it a try.
> 
> https://www.geeksforgeeks.org/auto-hide-or-auto-extend-floating-action-button-in-recyclerview-in-android/

@hieuwu That's a nice approach.
I've changed the code to make it work in such a mentioned way.
Please review.

2023-10-20 12:19 UTC, hieuwu approved these changes
LGTM

2023-10-20 13:35 UTC, mdrlzy approved these changes

2023-10-20 14:32 UTC, merged